import { StyleSheet } from "react-native";
import { theme } from "../../Theme/color";

export default StyleSheet.create({
  screenIntro: {
    marginTop: 20,
    marginBottom: 18,
    gap: 8,
  },
  screenIntroRtl: {
    alignItems: "flex-end",
  },
  screenEyebrow: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  screenDescription: {
    color: theme.ink,
    fontSize: 25,
    lineHeight: 34,
    fontWeight: "900",
  },
  addNoteCard: {
    backgroundColor: theme.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    borderTopWidth: 4,
    borderTopColor: theme.atractive,
    padding: 16,
    gap: 14,
    marginBottom: 18,
  },
  addNoteCardRtl: {
    alignItems: "flex-end",
  },
  addNoteTitle: {
    color: theme.ink,
    fontSize: 21,
    fontWeight: "900",
  },
  addNoteSubtitle: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  searchInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    paddingHorizontal: 15,
    paddingVertical: 14,
  },
  searchInputRowRtl: {
    flexDirection: "row-reverse",
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: theme.ink,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  actionRowRtl: {
    flexDirection: "row-reverse",
  },
  primaryButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primary,
    borderRadius: 8,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: theme.primaryHover,
  },
  primaryButtonActive: {
    backgroundColor: theme.atractive,
    borderColor: theme.success,
  },
  primaryButtonText: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  primaryButtonTextActive: {
    color: theme.surface,
  },
  secondaryButton: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: theme.panelElevated,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  secondaryButtonText: {
    color: theme.ink,
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  headerCard: {
    backgroundColor: theme.primary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.primaryHover,
    padding: 18,
    gap: 9,
    marginBottom: 18,
  },
  headerCardRtl: {
    alignItems: "flex-end",
  },
  headerEyebrow: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  headerTitle: {
    color: theme.ink,
    fontSize: 30,
    fontWeight: "900",
  },
  headerCount: {
    color: theme.ink,
    fontSize: 22,
    fontWeight: "900",
  },
  headerHint: {
    color: theme.ink,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  headerStatRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 6,
  },
  headerStatRowRtl: {
    flexDirection: "row-reverse",
  },
  headerStatPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  headerStatText: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  settingsStatCard: {
    backgroundColor: theme.panelElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    borderTopWidth: 4,
    borderTopColor: theme.atractive,
    padding: 18,
    gap: 8,
    marginBottom: 18,
  },
  settingsStatCardRtl: {
    alignItems: "flex-end",
  },
  settingsStatNumber: {
    color: theme.atractive,
    fontSize: 44,
    fontWeight: "900",
  },
  controlsCard: {
    backgroundColor: theme.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    paddingVertical: 16,
    marginBottom: 20,
  },
  controlsGroup: {
    gap: 10,
    marginBottom: 16,
  },
  controlsGroupLast: {
    marginBottom: 0,
  },
  controlsLabel: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    paddingHorizontal: 16,
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  chipsScrollContent: {
    paddingHorizontal: 16,
    gap: 10,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: theme.panelElevated,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  chipActive: {
    backgroundColor: theme.atractive,
    borderColor: theme.success,
  },
  chipText: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  chipTextActive: {
    color: theme.surface,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.divider,
  },
  sectionHeaderRtl: {
    flexDirection: "row-reverse",
  },
  sectionTitle: {
    color: theme.ink,
    fontSize: 23,
    fontWeight: "900",
  },
  sectionMeta: {
    color: theme.inkMuted,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  recentScrollContent: {
    paddingRight: 10,
  },
  recentCard: {
    width: 274,
    marginRight: 12,
  },
  noteCard: {
    backgroundColor: theme.panelElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    borderLeftWidth: 4,
    borderLeftColor: theme.primary,
    padding: 15,
    marginBottom: 12,
    gap: 14,
  },
  noteCardPinned: {
    borderColor: theme.atractive,
    borderLeftColor: theme.atractive,
    backgroundColor: theme.pinnedPanel,
  },
  noteTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  noteTopRowRtl: {
    flexDirection: "row-reverse",
  },
  coverCard: {
    width: 70,
    height: 70,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.divider,
  },
  coverEmoji: {
    fontSize: 30,
  },
  noteMain: {
    flex: 1,
    gap: 5,
  },
  noteMainRtl: {
    alignItems: "flex-end",
  },
  noteTitle: {
    color: theme.ink,
    fontSize: 19,
    fontWeight: "900",
  },
  noteTitleHighlight: {
    color: theme.atractive,
  },
  noteTitleFocus: {
    color: theme.primaryHover,
  },
  notePreview: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
  },
  noteMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  noteMetaRowRtl: {
    flexDirection: "row-reverse",
  },
  metaBadge: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  metaBadgeText: {
    color: theme.ink,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  labelRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  labelRowRtl: {
    flexDirection: "row-reverse",
  },
  labelBadge: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: theme.primaryMuted,
    borderWidth: 1,
    borderColor: theme.secondarySoft,
  },
  labelBadgeText: {
    color: theme.ink,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  noteActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  noteActionsVertical: {
    flexDirection: "column",
    alignItems: "center",
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  emptyState: {
    backgroundColor: theme.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    padding: 28,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  emptyStateRtl: {
    alignItems: "flex-end",
  },
  emptyTitle: {
    color: theme.ink,
    fontSize: 21,
    fontWeight: "900",
  },
  emptySubtitle: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  editorContent: {
    paddingBottom: 28,
  },
  editorTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  editorTopBarRtl: {
    flexDirection: "row-reverse",
  },
  editorActionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: theme.atractive,
  },
  editorActionText: {
    color: theme.surface,
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  editorTitle: {
    color: theme.ink,
    fontSize: 32,
    fontWeight: "900",
  },
  editorCard: {
    backgroundColor: theme.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    padding: 16,
    gap: 12,
    marginBottom: 16,
  },
  editorSectionTitle: {
    color: theme.ink,
    fontSize: 21,
    fontWeight: "900",
  },
  editorSectionHint: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  editorInput: {
    backgroundColor: theme.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    paddingHorizontal: 15,
    paddingVertical: 13,
    fontSize: 15,
    color: theme.ink,
  },
  editorBodyInput: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  textRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  textLtr: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  checklistRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  checklistRowRtl: {
    flexDirection: "row-reverse",
  },
  checklistText: {
    flex: 1,
    color: theme.ink,
    fontSize: 14,
  },
  checklistTextDone: {
    color: theme.inkMuted,
    textDecorationLine: "line-through",
  },
  coverOptionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  coverOption: {
    flex: 1,
    minHeight: 92,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: theme.divider,
  },
  coverOptionActive: {
    borderColor: theme.atractive,
  },
  dangerButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primaryMuted,
    borderRadius: 8,
    paddingVertical: 15,
    paddingHorizontal: 14,
  },
  dangerButtonText: {
    color: theme.ink,
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
});
