import { StyleSheet } from "react-native";
import { theme } from "../../Theme/color";

export default StyleSheet.create({
  screenIntro: {
    marginTop: 20,
    marginBottom: 18,
    gap: 8,
  },
  screenIntroRtl: {
    alignItems: "flex-end",
  },
  screenEyebrow: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  screenDescription: {
    color: theme.ink,
    fontSize: 22,
    lineHeight: 31,
    fontWeight: "900",
  },
  addNoteCard: {
    backgroundColor: theme.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 18,
    gap: 14,
    marginBottom: 18,
  },
  addNoteCardRtl: {
    alignItems: "flex-end",
  },
  addNoteTitle: {
    color: theme.ink,
    fontSize: 19,
    fontWeight: "900",
  },
  addNoteSubtitle: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  searchInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  searchInputRowRtl: {
    flexDirection: "row-reverse",
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: theme.ink,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  actionRowRtl: {
    flexDirection: "row-reverse",
  },
  primaryButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primary,
    borderRadius: 14,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  primaryButtonActive: {
    backgroundColor: theme.atractive,
    borderColor: theme.atractive,
  },
  primaryButtonText: {
    color: theme.ink,
    fontSize: 15,
    fontWeight: "900",
  },
  primaryButtonTextActive: {
    color: theme.surface,
  },
  secondaryButton: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderRadius: 14,
    backgroundColor: theme.panelElevated,
    borderWidth: 1,
    borderColor: theme.border,
  },
  secondaryButtonText: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  headerCard: {
    backgroundColor: theme.primary,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.atractive,
    padding: 18,
    gap: 8,
    marginBottom: 18,
  },
  headerCardRtl: {
    alignItems: "flex-end",
  },
  headerEyebrow: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  headerTitle: {
    color: theme.ink,
    fontSize: 30,
    fontWeight: "900",
  },
  headerCount: {
    color: theme.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  headerHint: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  headerStatRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 6,
  },
  headerStatRowRtl: {
    flexDirection: "row-reverse",
  },
  headerStatPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  headerStatText: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
  },
  settingsStatCard: {
    backgroundColor: theme.panelElevated,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    borderLeftWidth: 5,
    borderLeftColor: theme.atractive,
    padding: 18,
    gap: 8,
    marginBottom: 18,
  },
  settingsStatCardRtl: {
    alignItems: "flex-end",
    borderLeftWidth: 1,
    borderRightWidth: 5,
    borderRightColor: theme.atractive,
  },
  settingsStatNumber: {
    color: theme.atractive,
    fontSize: 42,
    fontWeight: "900",
  },
  controlsCard: {
    backgroundColor: theme.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    paddingVertical: 16,
    marginBottom: 20,
  },
  controlsGroup: {
    gap: 10,
    marginBottom: 16,
  },
  controlsGroupLast: {
    marginBottom: 0,
  },
  controlsLabel: {
    color: theme.inkMuted,
    fontSize: 12,
    fontWeight: "900",
    paddingHorizontal: 16,
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  chipsScrollContent: {
    paddingHorizontal: 16,
    gap: 10,
  },
  chip: {
    paddingHorizontal: 15,
    paddingVertical: 11,
    borderRadius: 13,
    backgroundColor: theme.panelElevated,
    borderWidth: 1,
    borderColor: theme.border,
  },
  chipActive: {
    backgroundColor: theme.atractive,
    borderColor: theme.atractive,
  },
  chipText: {
    color: theme.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  chipTextActive: {
    color: theme.surface,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionHeaderRtl: {
    flexDirection: "row-reverse",
  },
  sectionTitle: {
    color: theme.ink,
    fontSize: 22,
    fontWeight: "900",
  },
  sectionMeta: {
    color: theme.inkMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  recentScrollContent: {
    paddingRight: 10,
  },
  recentCard: {
    width: 270,
    marginRight: 14,
  },
  noteCard: {
    backgroundColor: theme.panelElevated,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
    marginBottom: 12,
    gap: 14,
  },
  noteCardPinned: {
    borderColor: theme.atractive,
    backgroundColor: theme.pinnedPanel,
  },
  noteTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  noteTopRowRtl: {
    flexDirection: "row-reverse",
  },
  coverCard: {
    width: 70,
    height: 70,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  coverEmoji: {
    fontSize: 30,
  },
  noteMain: {
    flex: 1,
    gap: 4,
  },
  noteMainRtl: {
    alignItems: "flex-end",
  },
  noteTitle: {
    color: theme.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  noteTitleHighlight: {
    color: theme.atractive,
  },
  noteTitleFocus: {
    letterSpacing: 0,
  },
  notePreview: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  noteMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  noteMetaRowRtl: {
    flexDirection: "row-reverse",
  },
  metaBadge: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  metaBadgeText: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  labelRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  labelRowRtl: {
    flexDirection: "row-reverse",
  },
  labelBadge: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: theme.primaryMuted,
  },
  labelBadgeText: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "900",
  },
  noteActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  noteActionsVertical: {
    flexDirection: "column",
    alignItems: "center",
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  emptyState: {
    backgroundColor: theme.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 28,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  emptyStateRtl: {
    alignItems: "flex-end",
  },
  emptyTitle: {
    color: theme.ink,
    fontSize: 20,
    fontWeight: "900",
  },
  emptySubtitle: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  editorContent: {
    paddingBottom: 28,
  },
  editorTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  editorTopBarRtl: {
    flexDirection: "row-reverse",
  },
  editorActionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: theme.atractive,
  },
  editorActionText: {
    color: theme.surface,
    fontSize: 14,
    fontWeight: "900",
  },
  editorTitle: {
    color: theme.ink,
    fontSize: 30,
    fontWeight: "900",
  },
  editorCard: {
    backgroundColor: theme.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 18,
    gap: 12,
    marginBottom: 18,
  },
  editorSectionTitle: {
    color: theme.ink,
    fontSize: 19,
    fontWeight: "900",
  },
  editorSectionHint: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  editorInput: {
    backgroundColor: theme.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 15,
    paddingVertical: 13,
    fontSize: 15,
    color: theme.ink,
  },
  editorBodyInput: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  textRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  textLtr: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  checklistRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.surface,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  checklistRowRtl: {
    flexDirection: "row-reverse",
  },
  checklistText: {
    flex: 1,
    color: theme.ink,
    fontSize: 14,
  },
  checklistTextDone: {
    color: theme.inkMuted,
    textDecorationLine: "line-through",
  },
  coverOptionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  coverOption: {
    flex: 1,
    minHeight: 92,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: theme.border,
  },
  coverOptionActive: {
    borderColor: theme.atractive,
  },
  dangerButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primaryMuted,
    borderRadius: 14,
    paddingVertical: 15,
  },
  dangerButtonText: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
  },
});
