import { StyleSheet } from "react-native";
import { theme } from "../Theme/color";

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  phoneShell: {
    flex: 1,
    backgroundColor: theme.canvas,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.divider,
    shadowColor: theme.shadow,
    shadowOpacity: 0.38,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 10,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 34,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.divider,
  },
  headerRowRtl: {
    flexDirection: "row-reverse",
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 1,
  },
  profileRowRtl: {
    flexDirection: "row-reverse",
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: theme.panelElevated,
    borderWidth: 2,
    borderColor: theme.primaryHover,
  },
  profileName: {
    fontSize: 19,
    fontWeight: "900",
    color: theme.ink,
    letterSpacing: 0,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerActionsRtl: {
    flexDirection: "row-reverse",
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  languageToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: theme.atractive,
    borderWidth: 1,
    borderColor: theme.success,
  },
  languageToggleRtl: {
    flexDirection: "row-reverse",
  },
  languageToggleText: {
    fontSize: 12,
    fontWeight: "900",
    color: theme.surface,
  },
  tabRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 4,
    marginTop: 18,
    marginBottom: 18,
    borderRadius: 8,
    backgroundColor: theme.panel,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  tabRowRtl: {
    flexDirection: "row-reverse",
  },
  tabInactive: {
    fontSize: 13,
    color: theme.inkMuted,
    paddingHorizontal: 17,
    paddingVertical: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  activeTabGroup: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minHeight: 48,
    borderRadius: 6,
    backgroundColor: theme.primary,
  },
  tabActive: {
    fontSize: 13,
    fontWeight: "900",
    color: theme.ink,
    textTransform: "uppercase",
  },
  tabIndicator: {
    width: 34,
    height: 3,
    borderRadius: 999,
    marginTop: 7,
    backgroundColor: theme.success,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  actionsRowRtl: {
    flexDirection: "row-reverse",
  },
  cardWrapper: {
    position: "relative",
    flex: 1,
  },
  cardPressable: {
    borderRadius: 8,
  },
  cardContainer: {
    backgroundColor: theme.panelElevated,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: 18,
    borderRadius: 8,
    minHeight: 164,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  cardImage: {
    width: 54,
    height: 54,
  },
  cardTitle: {
    marginTop: 14,
    fontSize: 18,
    fontWeight: "900",
    color: theme.ink,
    textAlign: "center",
  },
  cardOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 8,
    backgroundColor: "rgba(10,112,117,0.92)",
    borderWidth: 1,
    borderColor: theme.success,
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: 18,
  },
  actionIcon: {
    width: 40,
    height: 40,
  },
  actionLabel: {
    fontSize: 19,
    fontWeight: "900",
    color: theme.ink,
    textAlign: "left",
  },
  previewPanel: {
    marginTop: 2,
  },
  previewGrid: {
    flexDirection: "row",
    gap: 12,
  },
  previewGridRtl: {
    flexDirection: "row-reverse",
  },
  previewCard: {
    flex: 1,
    minHeight: 210,
    borderRadius: 8,
    backgroundColor: theme.panelElevated,
    borderWidth: 1,
    borderColor: theme.divider,
    borderTopWidth: 4,
    borderTopColor: theme.primaryHover,
    padding: 18,
    justifyContent: "space-between",
  },
  previewCardRtl: {
    alignItems: "flex-end",
  },
  previewIcon: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: theme.atractive,
    alignItems: "center",
    justifyContent: "center",
  },
  previewTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: theme.ink,
  },
  previewCount: {
    fontSize: 13,
    color: theme.inkMuted,
    lineHeight: 20,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  buttonRow: {
    alignItems: "center",
    marginTop: 20,
  },
  addButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.primary,
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 8,
    marginTop: 4,
    minWidth: 210,
    borderWidth: 1,
    borderColor: theme.primaryHover,
  },
  addButtonRtl: {
    flexDirection: "row-reverse",
  },
  addButtonText: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  addButtonTextRtl: {
    writingDirection: "rtl",
    textAlign: "right",
  },
  addButtonImage: {
    width: 18,
    height: 18,
    marginRight: 8,
  },
  addButtonImageRtl: {
    marginLeft: 5,
    marginRight: 0,
  },
  textLtr: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  textRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  centeredTextRtl: {
    textAlign: "center",
    writingDirection: "rtl",
  },
});
