import { StyleSheet } from "react-native";
import { theme } from "../Theme/color";

export default StyleSheet.create({
  screenBody: {
    flex: 1,
  },
  settingsIntroTitle: {
    color: theme.ink,
    fontSize: 23,
    fontWeight: "900",
    lineHeight: 31,
    maxWidth: 340,
  },
  settingsStage: {
    position: "relative",
    gap: 16,
    paddingBottom: 18,
  },
  settingsGlowLarge: {
    position: "absolute",
    width: 210,
    height: 210,
    borderRadius: 105,
    top: -30,
    right: -80,
    backgroundColor: theme.primary,
    opacity: 0.2,
  },
  settingsGlowSmall: {
    position: "absolute",
    width: 110,
    height: 110,
    borderRadius: 55,
    top: 122,
    left: -46,
    backgroundColor: theme.success,
    opacity: 0.12,
  },
  settingsHeroCard: {
    overflow: "hidden",
    backgroundColor: theme.panelElevated,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.divider,
    padding: 20,
    gap: 16,
    shadowColor: theme.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  settingsHeroCardRtl: {
    alignItems: "flex-end",
  },
  settingsHeroTopline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  settingsIconPlate: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primary,
    borderWidth: 1,
    borderColor: theme.atractive,
  },
  settingsIconPlateMuted: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  settingsKicker: {
    color: theme.success,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  settingsStatDial: {
    width: 132,
    height: 132,
    borderRadius: 66,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  settingsDialRing: {
    position: "absolute",
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 8,
    borderTopColor: theme.atractive,
    borderRightColor: theme.primaryHover,
    borderBottomColor: theme.divider,
    borderLeftColor: theme.success,
    opacity: 0.9,
  },
  settingsStatNumber: {
    color: theme.ink,
    fontSize: 46,
    fontWeight: "900",
    lineHeight: 54,
  },
  settingsHeroHint: {
    color: theme.inkMuted,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 22,
  },
  settingsPanel: {
    overflow: "hidden",
    backgroundColor: theme.panel,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
    gap: 14,
  },
  settingsPanelHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  settingsPanelHeaderRtl: {
    flexDirection: "row-reverse",
  },
  settingsHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  settingsSegment: {
    flexDirection: "row",
    gap: 10,
    padding: 5,
    borderRadius: 18,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  settingsSegmentRtl: {
    flexDirection: "row-reverse",
  },
  settingsLanguageButton: {
    flex: 1,
    minHeight: 64,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "transparent",
  },
  settingsLanguageButtonActive: {
    backgroundColor: theme.atractive,
    borderColor: theme.success,
  },
  settingsLanguageCode: {
    color: theme.inkSoft,
    fontSize: 11,
    fontWeight: "900",
  },
  settingsLanguageText: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  settingsLanguageTextActive: {
    color: theme.surface,
  },
  settingsStatusStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  settingsStatusStripRtl: {
    flexDirection: "row-reverse",
  },
  settingsStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.success,
  },
  settingsStatusText: {
    flex: 1,
    color: theme.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
});
