import { StyleSheet } from "react-native";
import { theme } from "../../Theme/color";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  phoneShell: {
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 22,
    overflow: "hidden",
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  screenScrollContent: {
    paddingBottom: 28,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: theme.panelElevated,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarLabel: {
    color: theme.inkMuted,
    fontSize: 14,
    fontWeight: "800",
  },
  screenIntro: {
    marginTop: 20,
    marginBottom: 18,
    gap: 8,
  },
  screenIntroRtl: {
    alignItems: "flex-end",
  },
  screenEyebrow: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  screenDescription: {
    color: theme.ink,
    fontSize: 25,
    lineHeight: 34,
    fontWeight: "900",
  },
  taskCard: {
    backgroundColor: theme.panelElevated,
    padding: 15,
    borderRadius: 8,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    borderWidth: 1,
    borderColor: theme.divider,
    borderLeftWidth: 4,
    borderLeftColor: theme.primaryHover,
  },
  taskCardRtl: {
    flexDirection: "row-reverse",
    borderLeftWidth: 1,
    borderRightWidth: 4,
    borderRightColor: theme.primaryHover,
  },
  taskTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: theme.ink,
  },
  taskHeader: {
    gap: 9,
    marginBottom: 18,
    backgroundColor: theme.primary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.primaryHover,
    padding: 18,
  },
  taskHeaderRtl: {
    alignItems: "flex-end",
  },
  sectionEyebrow: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  screenTitle: {
    color: theme.ink,
    fontSize: 32,
    fontWeight: "900",
  },
  taskMeta: {
    color: theme.ink,
    fontSize: 19,
    fontWeight: "900",
  },
  taskHint: {
    color: theme.ink,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  taskStatRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  taskStatRowRtl: {
    flexDirection: "row-reverse",
  },
  taskStatPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.divider,
  },
  taskStatText: {
    color: theme.atractive,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  composerCard: {
    backgroundColor: theme.panel,
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.divider,
    borderTopWidth: 4,
    borderTopColor: theme.atractive,
    marginBottom: 18,
  },
  composerCardRtl: {
    alignItems: "flex-end",
  },
  composerTitle: {
    color: theme.ink,
    fontSize: 21,
    fontWeight: "900",
    marginBottom: 4,
  },
  composerSubtitle: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
    fontWeight: "700",
  },
  textInput: {
    backgroundColor: theme.surface,
    color: theme.ink,
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    minHeight: 92,
    textAlignVertical: "top",
    fontSize: 16,
  },
  textInputRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  addButton: {
    backgroundColor: theme.atractive,
    alignItems: "center",
    borderRadius: 8,
    paddingVertical: 15,
    marginTop: 14,
  },
  addButtonDisabled: {
    backgroundColor: theme.border,
  },
  addButtonText: {
    color: theme.surface,
    fontWeight: "900",
    fontSize: 14,
    textTransform: "uppercase",
  },
  listContent: {
    flexGrow: 1,
    paddingBottom: 10,
  },
  emptyStateRtl: {
    alignItems: "flex-end",
  },
  emptyState: {
    backgroundColor: theme.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.divider,
    paddingHorizontal: 22,
    paddingVertical: 30,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 8,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  emptyTitle: {
    color: theme.ink,
    fontSize: 21,
    fontWeight: "900",
    marginBottom: 6,
  },
  emptySubtitle: {
    color: theme.inkMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    marginBottom: 18,
  },
  emptyButton: {
    backgroundColor: theme.atractive,
    paddingHorizontal: 18,
    paddingVertical: 13,
    borderRadius: 8,
  },
  emptyButtonText: {
    color: theme.surface,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  checkbox: {
    width: 30,
    height: 30,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: theme.atractive,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxCompleted: {
    backgroundColor: theme.atractive,
    borderColor: theme.success,
  },
  taskBody: {
    flex: 1,
    gap: 4,
  },
  taskBodyRtl: {
    alignItems: "flex-end",
  },
  taskTitleCompleted: {
    textDecorationLine: "line-through",
    color: theme.inkMuted,
  },
  taskStatus: {
    color: theme.inkMuted,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  deleteButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: theme.primaryMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  textLtr: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  textRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
});
